defaults:
  - base
  - model: graphsage
  - data: static_default
  - _self_

train:
  lr: 0.001
  epochs: 200
  save_every: 5         # save checkpoint every N epochs
  checkpoint_dir: ${paths.checkpoints}/${model._target_}
